### ISSUE TITLE
"HttpsErrorImpl: [syncContractArtifact] Missing parameter." Error while deploying contracts.

### ISSUE THREAD

**Issue by artbm** [antoinedc/hardhat-ethernal#10]
Hello, I've been trying to deploy my contracts on a mainnet fork with hardhat. In order to debug things, i'd love to use Ethernal with hardhat, but I keed getting this error. 

`arthur@arthur-TUF-ubuntu:~/Bureau/hardhat$ npx hardhat run scripts/deploy.js 
[Ethernal]  Logged in with <EMAIL>@gmail.com
[Ethernal]  Using default workspace "Mainnet Fork"
HttpsErrorImpl: [syncContractArtifact] Missing parameter.
    at new HttpsErrorImpl (/home/arthur/Bureau/hardhat/node_modules/@firebase/functions/src/api/error.ts:66:5)
    at _errorForResponse (/home/arthur/Bureau/hardhat/node_modules/@firebase/functions/src/api/error.ts:175:10)
    at Service.<anonymous> (/home/arthur/Bureau/hardhat/node_modules/@firebase/functions/src/api/service.ts:296:19)
    at step (/home/arthur/Bureau/hardhat/node_modules/@firebase/functions/node_modules/tslib/tslib.js:143:27)
    at Object.next (/home/arthur/Bureau/hardhat/node_modules/@firebase/functions/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/home/arthur/Bureau/hardhat/node_modules/@firebase/functions/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'unknown',
  details: undefined
}
`

I did everything exactly as said in the documentation. Feel free to ask if you need more informations.

**Comment by antoinedc** [comment]
Hi, can you show me that code that pushes to Ethernal, please?
Also, is the name parameter that you pass to the push function exactly the same than the contract name?

**Comment by wiredmatt** [comment]
Hi, I'm having this issue as well trying to deploy an ERC-721 contract (it worked fine with an ERC-20), it deploys fine using Hardhat but if I try to push the artifact with ethernal it outputs the following:

```
[Ethernal]  Logged in with mateocarriqui7@gmail.com
[Ethernal]  Using default workspace "aquarium-wars"
An unexpected error occurred:

HttpsErrorImpl: [syncContractArtifact] Missing parameter.
    at new HttpsErrorImpl (/home/system32uwu/repos/aquarium-wars/node_modules/@firebase/functions/src/api/error.ts:66:5)
    at _errorForResponse (/home/system32uwu/repos/aquarium-wars/node_modules/@firebase/functions/src/api/error.ts:175:10)
    at Service.<anonymous> (/home/system32uwu/repos/aquarium-wars/node_modules/@firebase/functions/src/api/service.ts:296:19)
    at step (/home/system32uwu/repos/aquarium-wars/node_modules/tslib/tslib.js:143:27)
    at Object.next (/home/system32uwu/repos/aquarium-wars/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/home/system32uwu/repos/aquarium-wars/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'invalid-argument',
  details: undefined
}
error Command failed with exit code 1.
```

Code:

```typescript
task('deploy-nft', 'Deploys a new NFT collection')
  .addPositionalParam(
    'baseUri',
    'Base URI',
    undefined,
    types.string,
    false
  )
  .addPositionalParam(
    'name',
    'Name of the collection',
    undefined,
    types.string,
    false
  )
  .addPositionalParam(
    'symbol',
    'Symbol of the collection',
    undefined,
    types.string,
    false
  )
  .addPositionalParam('price', 'Mint Price', undefined, types.int, false)
  .addPositionalParam(
    'maxmint',
    'Max amount allowed to be minted at once',
    undefined,
    types.int,
    false
  )
  .addPositionalParam(
    'reserved',
    'Amount reserved for events and giveaways',
    undefined,
    types.int,
    false
  )
  .addPositionalParam(
    'supply',
    'Maximum supply',
    undefined,
    types.int,
    false
  )
  .setAction(
    async (
      { baseUri, name, symbol, price, maxmint, reserved, supply },
      hre
    ) => {
      const AQLF = await hre.ethers.getContractFactory('AquariumLifeForm')
      const aqlf = await AQLF.deploy(
        baseUri,
        name,
        symbol,
        price,
        maxmint,
        reserved,
        supply
      )

      await aqlf.deployed()

      await hre.ethernal.push({
        name: name,
         address: aqlf.address,
       })

      console.log(`${await aqlf.symbol()} deployed to:`, aqlf.address)
    }
  )

```

**Comment by antoinedc** [comment]
Hey, can you double check and make sure that `name` & `aqlf.address` are defined, please?

**Comment by wiredmatt** [comment]
Yeah, 

```javascript
console.log(name) 
console.log(aqlf.address)
```

returns 

```
Mutant Anchovies
0x5FbDB2315678afecb367f032d93F642f64180aa3
```

**Comment by antoinedc** [comment]
Ok, thanks, can you delete the `artifacts` folder and try to recompile, deploy and push again, please?

**Comment by wiredmatt** [comment]
I did a couple times but no luck, I even tried a new project, but it seems that it fails to build tokens that are not ERC-20 ones, does it work for you?

**Comment by antoinedc** [comment]
Hey, sorry for the late reply, I was away last week. Yes it works for me for all kind of tokens.
Any way you could share the new project that you setup and doesn't work? So I can reproduce.

**Comment by wiredmatt** [comment]
Hi! I deleted npm and yarn cache, deleted yarn.lock, reinstalled ethernal globally, reinstalled dependencies and it magically worked now  ¯\\_(ツ)_/¯.

**Comment by antoinedc** [comment]
To file under "Javascript mysteries" I guess 🤣
Glad it works anyway!

**Comment by Jhoscy** [comment]
@antoinedc I've tried deleting npm cache, artifacts, package-lock, reinstalled all the node_modules but I've got the same error as @system32uwu. I've also checked that the name and the address have values (not undefined) and that the name is the same as defined in the contract. What can I do to make it works without this exception?: 

HttpsErrorImpl: [syncContractArtifact] Missing parameter.
    at new HttpsErrorImpl (/home/joscy/Scrivania/Projects/hardhat-examples/hardhat-sample/node_modules/@firebase/functions/src/api/error.ts:66:5)
    at _errorForResponse (/home/joscy/Scrivania/Projects/hardhat-examples/hardhat-sample/node_modules/@firebase/functions/src/api/error.ts:175:10)
    at Service.<anonymous> (/home/joscy/Scrivania/Projects/hardhat-examples/hardhat-sample/node_modules/@firebase/functions/src/api/service.ts:296:19)
    at step (/home/joscy/Scrivania/Projects/hardhat-examples/hardhat-sample/node_modules/@firebase/functions/node_modules/tslib/tslib.js:143:27)
    at Object.next (/home/joscy/Scrivania/Projects/hardhat-examples/hardhat-sample/node_modules/@firebase/functions/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/home/joscy/Scrivania/Projects/hardhat-examples/hardhat-sample/node_modules/@firebase/functions/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'invalid-argument',
  details: undefined
}

**Comment by Jhoscy** [comment]
UPDATE: I've found the problem. Make sure that the name passed to ethernal push: (contract: ContractInput) match exaclty the contract's name and not any other formatted name string stored as info into the contract as variable (for example I used to pass the name "My Perfect Token" that was different from the class contract name definition).

**Comment by antoinedc** [comment]
Ah yes, always forget about this one :) there is a line about it in the doc & in the repo, but i'll try to make it more prominent/clearer. I know it's not very convenient but I haven't found more automatic way to detect artifacts & deployment addresses with Hardhat.
