### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'advancedOptions') when calling eth_sendTransaction too fast

### ISSUE THREAD

**Issue by krasi-georgiev** [antoinedc/hardhat-ethernal#14]
this happens quite often when sending a TX too fast to a hardhat fork. I use just the usual net dial method to know when the network is ready to receive requests.

see logs below

<details>
<summary>Details</summary>

```
	testutil.go:88: npx hardhat node --fork https://eth-mainnet.alchemyapi.io/v2/. --fork-block-number 13978523
    testutil.go:102: error connecting will retry
    testutil.go:102: error connecting will retry
    testutil.go:102: error connecting will retry
    testutil.go:88: Started HTTP and WebSocket JSON-RPC server at http://127.0.0.1:8545/
    testutil.go:88: 
    testutil.go:88: Accounts
    testutil.go:88: ========
    testutil.go:88: 
    testutil.go:88: WARNING: These accounts, and their private keys, are publicly known.
    testutil.go:88: Any funds sent to them on Mainnet or any other live network WILL BE LOST.
    testutil.go:88: 
    testutil.go:88: Account #0: 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 (10000 ETH)
    testutil.go:88: Private Key: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
    testutil.go:88: 
    testutil.go:88: Account #1: 0x70997970c51812dc3a010c7d01b50e0d17dc79c8 (10000 ETH)
    testutil.go:88: Private Key: 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
    testutil.go:88: 
    testutil.go:88: Account #2: 0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc (10000 ETH)
    testutil.go:88: Private Key: 0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a
    testutil.go:88: 
    testutil.go:88: Account #3: 0x90f79bf6eb2c4f870365e785982e1f101e93b906 (10000 ETH)
    testutil.go:88: Private Key: 0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6
    testutil.go:88: 
    testutil.go:88: Account #4: 0x15d34aaf54267db7d7c367839aaf71a00a2c6a65 (10000 ETH)
    testutil.go:88: Private Key: 0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a
    testutil.go:88: 
    testutil.go:88: Account #5: 0x9965507d1a55bcc2695c58ba16fb37d819b0a4dc (10000 ETH)
    testutil.go:88: Private Key: 0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba
    testutil.go:88: 
    testutil.go:88: Account #6: 0x976ea74026e726554db657fa54763abd0c3a0aa9 (10000 ETH)
    testutil.go:88: Private Key: 0x92db14e403b83dfe3df233f83dfa3a0d7096f21ca9b0d6d6b8d88b2b4ec1564e
    testutil.go:88: 
    testutil.go:88: Account #7: 0x14dc79964da2c08b23698b3d3cc7ca32193d9955 (10000 ETH)
    testutil.go:88: Private Key: 0x4bbbf85ce3377467afe5d46f804f221813b2bb87f24d81f60f1fcdbf7cbf4356
    testutil.go:88: 
    testutil.go:88: Account #8: 0x23618e81e3f5cdf7f54c3d65f7fbc0abf5b21e8f (10000 ETH)
    testutil.go:88: Private Key: 0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97
    testutil.go:88: 
    testutil.go:88: Account #9: 0xa0ee7a142d267c1f36714e4a8f75612f20a79720 (10000 ETH)
    testutil.go:88: Private Key: 0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6
    testutil.go:88: 
    testutil.go:88: Account #10: 0xbcd4042de499d14e55001ccbb24a551f3b954096 (10000 ETH)
    testutil.go:88: Private Key: 0xf214f2b2cd398c806f84e317254e0f0b801d0643303237d97a22a48e01628897
    testutil.go:88: 
    testutil.go:88: Account #11: 0x71be63f3384f5fb98995898a86b02fb2426c5788 (10000 ETH)
    testutil.go:88: Private Key: 0x701b615bbdfb9de65240bc28bd21bbc0d996645a3dd57e7b12bc2bdf6f192c82
    testutil.go:88: 
    testutil.go:88: Account #12: 0xfabb0ac9d68b0b445fb7357272ff202c5651694a (10000 ETH)
    testutil.go:88: Private Key: 0xa267530f49f8280200edf313ee7af6b827f2a8bce2897751d06a843f644967b1
    testutil.go:88: 
    testutil.go:88: Account #13: 0x1cbd3b2770909d4e10f157cabc84c7264073c9ec (10000 ETH)
    testutil.go:88: Private Key: 0x47c99abed3324a2707c28affff1267e45918ec8c3f20b8aa892e8b065d2942dd
    testutil.go:88: 
    testutil.go:88: Account #14: 0xdf3e18d64bc6a983f673ab319ccae4f1a57c7097 (10000 ETH)
    testutil.go:88: Private Key: 0xc526ee95bf44d8fc405a158bb884d9d1238d99f0612e9f33d006bb0789009aaa
    testutil.go:88: 
    testutil.go:88: Account #15: 0xcd3b766ccdd6ae721141f452c550ca635964ce71 (10000 ETH)
    testutil.go:88: Private Key: 0x8166f546bab6da521a8369cab06c5d2b9e46670292d85c875ee9ec20e84ffb61
    testutil.go:88: 
    testutil.go:88: Account #16: 0x2546bcd3c84621e976d8185a91a922ae77ecec30 (10000 ETH)
    testutil.go:88: Private Key: 0xea6c44ac03bff858b476bba40716402b03e41b8e97e276d1baec7c37d42484a0
    testutil.go:88: 
    testutil.go:88: Account #17: 0xbda5747bfd65f08deb54cb465eb87d40e51b197e (10000 ETH)
    testutil.go:88: Private Key: 0x689af8efa8c651a91ad287602527f3af2fe9f6501a7ac4b061667b5a93e037fd
    testutil.go:88: 
    testutil.go:88: Account #18: 0xdd2fd4581271e230360230f9337d5c0430bf44c0 (10000 ETH)
    testutil.go:88: Private Key: 0xde9be858da4a475276426320d5e9262ecfc3ba460bfac56360bfa6c4c28b4ee0
    testutil.go:88: 
    testutil.go:88: Account #19: 0x8626f6940e2eb28930efb4cef49b2d1f2c9c1199 (10000 ETH)
    testutil.go:88: Private Key: 0xdf57089febbacf7ba0bc227dafbffa9fc08a93fdc68e1e42411a14efcf23656e
    testutil.go:88: 
    testutil.go:88: WARNING: These accounts, and their private keys, are publicly known.
    testutil.go:88: Any funds sent to them on Mainnet or any other live network WILL BE LOST.
    testutil.go:88: 
    testutil.go:88: hardhat_setBalance
    testutil.go:88: eth_getBalance
    testutil.go:88: hardhat_impersonateAccount
    testutil.go:88: [Ethernal]  Logged in with krasi.root@gmail.com
    testutil.go:88: eth_sendTransaction
    testutil.go:88:   Contract call:   <UnrecognizedContract>
    testutil.go:88:   Transaction:     0xf8e1011de7d48707affe0838d4311807055fefc69aecd3ad8ebf658dcfeded69
    testutil.go:88:   From:            0xa3c5a1e09150b75ff251c1a7815a07182c3de2fb
    testutil.go:88:   To:              0xf403c135812408bfbe8713b5a23a04b3d48aae31
    testutil.go:88:   Value:           0 ETH
    testutil.go:88:   Gas used:        21896 of 30000000
    testutil.go:88:   Block #13978524: 0x8cdafbe0bb57df31c96902f71b2b1168b9e0629eb95c9f8387d2a01bca7865e3
    testutil.go:88: 
    testutil.go:88: 
    testutil.go:88: /home/krasi/src/github.com/cryptoriums/convex_bot/node_modules/hardhat-ethernal/src/Ethernal.ts:93
    testutil.go:88:         if (this.db.workspace.advancedOptions?.tracing != 'hardhat') return;
    testutil.go:88:                               ^
    testutil.go:88: TypeError: Cannot read properties of undefined (reading 'advancedOptions')
    testutil.go:88:     at Proxy.traceHandler (/home/krasi/src/github.com/cryptoriums/convex_bot/node_modules/hardhat-ethernal/src/Ethernal.ts:93:31)
    testutil.go:88:     at /home/krasi/src/github.com/cryptoriums/convex_bot/node_modules/hardhat-ethernal/src/index.ts:27:18
    testutil.go:88:     at /home/krasi/src/github.com/cryptoriums/convex_bot/node_modules/hardhat/src/internal/core/runtime-environment.ts:87:13
    testutil.go:88:     at EthModule._runHardhatNetworkMessageTraceHooks (/home/krasi/src/github.com/cryptoriums/convex_bot/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1650:13)
    testutil.go:88:     at EthModule._logSingleTransaction (/home/krasi/src/github.com/cryptoriums/convex_bot/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1597:16)
    testutil.go:88:     at EthModule._handleMineBlockResults (/home/krasi/src/github.com/cryptoriums/convex_bot/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1541:7)
    testutil.go:88:     at EthModule._sendTransactionAndReturnHash (/home/krasi/src/github.com/cryptoriums/convex_bot/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1516:7)
    testutil.go:88:     at HardhatNetworkProvider._sendWithLogging (/home/krasi/src/github.com/cryptoriums/convex_bot/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:138:22)
    testutil.go:88:     at HardhatNetworkProvider.request (/home/krasi/src/github.com/cryptoriums/convex_bot/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:115:18)
    testutil.go:88:     at JsonRpcHandler._handleRequest (/home/krasi/src/github.com/cryptoriums/convex_bot/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:20)
    main_test.go:114: main_test.go:114:
        
         unexpected error: Post "http://127.0.0.1:8545/": read tcp 127.0.0.1:37290->127.0.0.1:8545: read: connection reset by peer
```

</details>

**Comment by antoinedc** [comment]
Ah I see. You send the request while the plugin hasn't finished initializing yet, that's why it throws the error.
I'll push a fix to check for that and display a message. Thanks for the report!

Not sure how important that is for you, but if you want to make sure the plugin is initialized before sending requests, you can set in the hardhat config:
```
extendEnvironment((hre) => {
  hre.ethernalSync = false;
});
```
And then start the plugin whenever you are ready with:
```
await hre.ethernal.startListening()
```

**Comment by antoinedc** [comment]
Can you update to 0.3.13 and let me know, please? I pushed a fix.

**Comment by krasi-georgiev** [comment]
yes now all good
