### ISSUE TITLE
cannot push artifacts

### ISSUE THREAD

**Issue by strainz420** [antoinedc/hardhat-ethernal#20]
Hello,
since a few days, I am unable to push my artifacts with 
`hre.ethernal.push`

Times out with following error:
```
HttpsErrorImpl: unknown
    at new HttpsErrorImpl (node_modules/@firebase/functions/src/api/error.ts:66:5)
    at _errorForResponse (node_modules/@firebase/functions/src/api/error.ts:175:10)
    at Service.<anonymous> (node_modules/@firebase/functions/src/api/service.ts:276:19)
    at step (node_modules/tslib/tslib.js:141:27)
    at Object.next node_modules/tslib/tslib.js:122:57)
    at fulfilled (node_modules/tslib/tslib.js:112:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'unknown',
  details: undefined
```

**Comment by antoinedc** [comment]
Hi,

Could you give it another try, please? I upgraded the server so it shouldn't timeout anymore

**Comment by strainz420** [comment]
still remains.
resetting workspace and deploying works, only the artifacts time out

**Comment by antoinedc** [comment]
Ok what about now? 🤞

**Comment by strainz420** [comment]
works👌 thank you
