### ISSUE TITLE
Apparent transaction interference in new Ethernal workspace. After launching local network with `hh node` workspace fills up with un-recognized transactions and a high block number

### ISSUE THREAD

**Issue by afinetooth** [antoinedc/hardhat-ethernal#26]
Brief description:

- After launching local network with hh node workspace fills up with un-recognized transactions and a high block number.
- Running `hh node` errors and exits after throwing many warnings like: `Received invalid block tag 10962642. Latest block number is 0`

---

(Also submitted this today in Discord.)

Hello. Thanks for Ethernal. It's exactly what I've been looking for. 

Sadly, I'm having a tough issue I can't resolve and it's driving me nuts:

The result is the same as this user mentions in Discord, here:
https://discord.com/channels/821316469974761493/821316471615389708/961729264779161700

Hardhat Network throws a million errors like:
`Received invalid block tag 10962642. Latest block number is 0`, then exits.

I'm using the `hardhat-ethernal` plugin. Followed the instructions carefully. Even created a couple of different workspaces, but with the same results.

I feel like what's happening is transaction interference from outside of my workspace. Is this possible?

Each time, after change something to re-test, I reset my workspace with:

`hh console`

```
reset = await hre.ethernal.resetWorkspace("TheOmniscientOrange");
[Ethernal]  Logged in with james@allseeinglemon.io
[Ethernal]  Using default workspace "TheOmniscientOrange"
[Ethernal]  Resetting workspace "TheOmniscientOrange"...
[Ethernal]  Workspace "TheOmniscientOrange" has been reset!
.exit
```

Then I restart Hardhat Network with `hh node` and get something like this:

```
Started HTTP and WebSocket JSON-RPC server at http://127.0.0.1:8545/

Accounts
========

WARNING: These accounts, and their private keys, are publicly known.
Any funds sent to them on Mainnet or any other live network WILL BE LOST.

Account #0: 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 (10000 ETH)
Private Key: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

Account #1: 0x70997970c51812dc3a010c7d01b50e0d17dc79c8 (10000 ETH)
Private Key: 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d

[...]

Account #18: 0xdd2fd4581271e230360230f9337d5c0430bf44c0 (10000 ETH)
Private Key: 0xde9be858da4a475276426320d5e9262ecfc3ba460bfac56360bfa6c4c28b4ee0

Account #19: 0x8626f6940e2eb28930efb4cef49b2d1f2c9c1199 (10000 ETH)
Private Key: 0xdf57089febbacf7ba0bc227dafbffa9fc08a93fdc68e1e42411a14efcf23656e

WARNING: These accounts, and their private keys, are publicly known.
Any funds sent to them on Mainnet or any other live network WILL BE LOST.

[Ethernal]  Logged in with james@allseeinglemon.io
eth_blockNumber
[Ethernal]  Using default workspace "TheOmniscientOrange"
[Ethernal]  Resetting workspace "TheOmniscientOrange"...
[Ethernal]  Workspace "TheOmniscientOrange" has been reset!
[Ethernal]  Synced block #10962642
eth_accounts
eth_chainId
eth_accounts
eth_chainId
eth_call

  Received invalid block tag 10962642. Latest block number is 0

eth_accounts
eth_chainId
eth_accounts
eth_chainId
eth_call

  Received invalid block tag 10962642. Latest block number is 0

eth_accounts
eth_chainId
eth_accounts
eth_chainId
eth_call

  Received invalid block tag 10962642. Latest block number is 0

[then same thing a million more times, sometimes with increasing block numbers]

[then error and exit, something like this:]

eth_call

  Received invalid block tag 10962806. Latest block number is 0

eth_call

  Received invalid block tag 10962848. Latest block number is 0

eth_call

  Received invalid block tag 10962843. Latest block number is 0

eth_chainId (4)
eth_accounts (4)

/Users/jameskessler/Workspace/2022/crypto/projects/allseeinglemon/allseeinglemon/contracts/node_modules/@firebase/functions/src/api/error.ts:66
    super(message);
    ^
Error: deadline-exceeded
    at new HttpsErrorImpl (/Users/jameskessler/Workspace/2022/crypto/projects/allseeinglemon/allseeinglemon/contracts/node_modules/@firebase/functions/src/api/error.ts:66:5)
    at Timeout._onTimeout (/Users/jameskessler/Workspace/2022/crypto/projects/allseeinglemon/allseeinglemon/contracts/node_modules/@firebase/functions/src/api/service.ts:70:14)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

When I reset the workspace, I can see my workspace clear until it contains no data.

Then, suddenly, upon starting `hh node`, it fills up with transactions, and jumps to a high block number, like `10962642`, even though I am not forking mainnet or anything like that. And I'm not running anything else in the background. I even re-booted my machine to make sure.

I also see transactions I have nothing to do with, with addresses and ETH amounts I don't recognize (see attached screenshots below for some examples).

In case it helps, here's my `hardhat-config.js`:

```
[...]
require('hardhat-ethernal');

[...]

module.exports = {
  solidity: "0.8.4",
  defaultNetwork: "rinkeby",
  networks: {
    hardhat: {
      chainId: 1337
    },
    rinkeby: {
      url: API_URL,
      accounts: [PRIVATE_KEY]
    }
  },
  etherscan: {
    apiKey: ETHERSCAN_API_KEY
  },
  ethernal: {
    email: process.env.ETHERNAL_EMAIL,
    password: process.env.ETHERNAL_PASSWORD,
    resetOnStart: "TheOmniscientOrange"
  }
};
```

I've created two (2) different workspaces in Ethernal (hosted), testing theories:

1) afinetooth@gmail.com / http://127.0.0.1:8545 ("Localhost")
2) james@allseeinglemon.io / http://127.0.0.1:8545 ("TheOmniscientOrange")

I clicked "chose from  available (networks)" when I signed up, and chose the `http` version of my local network URL:
`http://127.0.0.1:8545`

I changed the name the second time, thinking "Localhost" is probably too common and I might be having some namespace collision.

Any help is greatly appreciated. Happy to create a paying account, but I need to get it working first.

**Comment by afinetooth** [comment]
Another detail:

The only thing I can do to prevent this from happening is set `disableSync: true` in my `hardhat-config.js`:

```
[...]
ethernal: {
    [...]
    disableSync: true
  }
[...]
```

**Comment by afinetooth** [comment]
## From Discord:

```
Antoine | Ethernal — Today at 5:37 AM
Hey James, thanks for all the details, I'm looking into it now
```

```
Antoine | Ethernal — Today at 5:43 AM
Can you try removing the "defaultNetwork" field or running hh node --network hardhat ? I think what you are seeing is Ethernal syncing rinkeby blocks
```

**Comment by afinetooth** [comment]
## From Discord

```
JamesLemon — Today at 3:41 PM
Thank you, @Antoine | Ethernal! That seems to have worked!

I guess that's just an oversight on my part, since I had defaultNetwork set to rinkeby in my hardhat-config.js.
After installing the hh shortcut I got used to running hh node to get a local blockchain running.
Thanks for noticing that in my config details. Sometimes it takes fresh eyes. 🙏 
```
