### ISSUE TITLE
Error HH604: Error running JSON-RPC server: ERROR processing

### ISSUE THREAD

**Issue by qSlnz** [antoinedc/hardhat-ethernal#4]
I try to install hardhat-ethernal, but when I put the ```import hardhat-ethernal``` in the hardhat config file, I then got the error on my deploy file

> Error HH604: Error running JSON-RPC server: ERROR processing /home/nathan/ethereum/game/packages/hardhat/deploy/120_deploy_packages.ts:
> Error: invalid signer (argument="signer", value="0x70997970C51812dc3A010C7d01b50e0d17dc79C8", code=INVALID_ARGUMENT, version=contracts/5.1.1)

The line that raise the error in my deploy file:

```typescript
  const diamondContract = ((await ethers.getContractAt(
      "Diamond",
      diamondAddress,
      admin,
  )) as unknown) as Diamond;
```

I'm using hardhat-deploy and hardhat-deploy-ethers. If I remove the import hardhat-ethernal  it's working again. Any idea how to fix this please?

**Comment by antoinedc** [comment]
Hi,

Can you put the content of your Hardhat config file here, please?

**Comment by qSlnz** [comment]
Hi,

```typescript
import "@typechain/hardhat";
import "@nomiclabs/hardhat-waffle";
import "@nomiclabs/hardhat-ethers";
import "hardhat-deploy";
import "hardhat-ethernal";

import {
    HardhatRuntimeEnvironment,
    HardhatUserConfig,
    NetworksUserConfig,
    SolidityUserConfig,
} from "hardhat/types";



// Import secret keys
import local from "./.local.config";

/*****************
 * SHOULD BE SET *
 *****************/

// Network use on deploiement
const defaultNetwork = "localhost";

// Infura ID key if infura provider is use
const INFURA_API_KEY = local.InfuraAPIKey;

/***********
 * ACCOUNT *
 ***********/

const namedAccounts = {
    deployer: 0,
    admin: 1,
    player1: 2,
};

/************
 * NETWORKS *
 ************/

const networks: NetworksUserConfig = {
    localhost: {
        url: "http://localhost:8545",
    },
};

/*************
 * COMPILERS *
 *************/
let appCompilers: SolidityUserConfig = {
    compilers: [
        {
            version: "0.5.5",
            settings: {
                optimizer: {
                    enabled: true,
                    runs: 200,
                },
            },
        },
        {
            version: "0.6.7",
            settings: {
                optimizer: {
                    enabled: true,
                    runs: 200,
                },
            },
        },
        {
            version: "0.7.6",
            settings: {
                optimizer: {
                    enabled: true,
                    runs: 200,
                },
            },
        },
        {
            version: "0.8.3",
            settings: {
                optimizer: {
                    enabled: true,
                    runs: 200,
                },
            },
        },
    ],
};

/**********
 * EXPORT *
 **********/

const config: HardhatUserConfig = {
    defaultNetwork: defaultNetwork,
    networks: networks,
    namedAccounts: namedAccounts,
    solidity: appCompilers,
    typechain: {
        outDir: "artifacts/typechain",
        target: "ethers-v5",
    },
    mocha: {
        timeout: 2000,
    },
    paths: {
        artifacts: "artifacts",
        sources: "contracts",
        tests: "test",
        cache: "cache",
        deploy: "deploy",
        deployments: "deployments",
    },
};


export default config;


// module.exports = {};
```

**Comment by antoinedc** [comment]
I don't see `hardhat-deploy-ethers` in your config file. Is it in the deploy file?

`hardhat-ethernal`depends on `hardhat-ethers`, and according to the doc here: https://hardhat.org/plugins/hardhat-deploy-ethers.html#installation, that means that `hardhat-deploy-ethers` should be installed in a specific way.
Can you take a look at those instructions and install it accordingly, please? 

If you've done it already, or if the issue doesn't go away, could you put your deploy file (the one that errors out) here as well, please?

**Comment by qSlnz** [comment]
Thanks for your reponse. I've added `hardhat-deploy-ethers` in the config file but still have the issue. I think my hardhat-deploy-ethers is correctly install, but I'm new so maybe I made a mistake I don't see. Here is my package.json, just to be sure:

```
{
    "name": "@project73/hardhat",
    "version": "1.0.0",
    "main": "index.js",
    "license": "MIT",
    "dependencies": {
    },
    "scripts": {
        "chain": "hh node --hostname 0.0.0.0 --show-accounts --network hardhat",
        "fork": "hh node --fork https://mainnet.infura.io/v3/hide",
        "test": "hh test --network hardhat --deploy-fixture",
        "compile": "hh compile",
        "deploy": "hh deploy",
        "build": "hh deploy",
        "watch": "node scripts/watch.js",
        "accounts": "hh accounts",
        "balance": "hh balance",
        "send": "hh send",
        "generate": "hh generate",
        "account": "hh account",
        "prettier:solidity": "./node_modules/.bin/prettier --write contracts/**/*.sol"
    },
    "devDependencies": {
        "@nomiclabs/hardhat-ethers": "yarn:hardhat-deploy-ethers",
        "@nomiclabs/hardhat-waffle": "^2.0.1",
        "@typechain/ethers-v5": "^7.0.0",
        "@typechain/hardhat": "^2.0.0",
        "@types/chai": "latest",
        "@types/chalk": "latest",
        "@types/fs-extra": "latest",
        "@types/mocha": "latest",
        "@types/node": "latest",
        "chai": "latest",
        "eslint": "latest",
        "eslint-config-airbnb": "latest",
        "eslint-config-prettier": "latest",
        "eslint-plugin-babel": "latest",
        "eslint-plugin-prettier": "latest",
        "ethereum-waffle": "^3.3.0",
        "ethers": "^5.1.4",
        "fs-extra": "latest",
        "hardhat": "^2.2.1",
        "hardhat-deploy": "^0.7.5",
        "hardhat-deploy-ethers": "^0.3.0-beta.7",
        "hardhat-ethernal": "^0.2.3",
        "mocha": "latest",
        "prettier": "latest",
        "prettier-plugin-solidity": "latest",
        "ramda": "latest",
        "solhint-plugin-prettier": "latest",
        "ts-generator": "latest",
        "ts-node": "latest",
        "typechain": "^5.0.0",
        "typescript": "^4.2.4"
    }
}

```

My deploy files are big so I will link them.
Here is the file where I deploy diamond contract (line 81)
https://github.com/qSlnz/game/blob/main/packages/hardhat/deploy/100_deploy_Universe.ts 
Here is the file that raise the error when I try to retrieve the deployed diamond contract information (line 111)
https://github.com/qSlnz/game/blob/main/packages/hardhat/deploy/120_deploy_packages.ts

**Comment by antoinedc** [comment]
Ok, it looks fine, yes.

Can you try passing a string, in your `getContractAt()` call, as the third parameter? It looks like the value that you are passing (that is coming from `getNamedAccount()`) might not be compatible.
Maybe you can give it try first by hardcoding the address there (`0x70997970C51812dc3A010C7d01b50e0d17dc79C8`), and if that works find a way to get it from the admin object.

**Comment by qSlnz** [comment]
got a solution. I think there is somewhere a link that allows to retrieve the Signer object from a string address, and hardhat-ethernal seems to not use this link so it cant retrieve the Signer. So I try to pass directly the Signer object instead of the address string and it's working. Here is the solution:

```typescript
        let adminSigner = await ethers.getSigner(admin);
        const diamondContract = ((await ethers.getContractAt(
            "Diamond",
            diamondAddress,
            adminSigner ,
        )) as unknown) as Diamond;
```

Also I put here the full error log (my bad I should have put it at the beginning) maybe it could help you to add this feature
```
Error HH604: Error running JSON-RPC server: ERROR processing /home/nathan/test/game/packages/hardhat/deploy/120_deploy_packages.ts:
Error: invalid signer (argument="signer", value="0x70997970C51812dc3A010C7d01b50e0d17dc79C8", code=INVALID_ARGUMENT, version=contracts/5.1.1)
    at Logger.makeError (/home/nathan/test/game/node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
    at Logger.throwError (/home/nathan/test/game/node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
    at Logger.throwArgumentError (/home/nathan/test/game/node_modules/@ethersproject/logger/src.ts/index.ts:221:21)
    at new ContractFactory (/home/nathan/test/game/node_modules/@ethersproject/contracts/src.ts/index.ts:1130:20)
    at getContractFactoryByAbiAndBytecode (/home/nathan/test/game/node_modules/hardhat-ethernal/node_modules/@nomiclabs/hardhat-ethers/src/internal/helpers.ts:259:10)
    at getContractAt (/home/nathan/test/game/node_modules/hardhat-ethernal/node_modules/@nomiclabs/hardhat-ethers/src/internal/helpers.ts:272:27)
    at Object.func (/home/nathan/test/game/packages/hardhat/deploy/120_deploy_packages.ts:112:35)
    at DeploymentsManager.executeDeployScripts (/home/nathan/test/game/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1006:22)
    at DeploymentsManager.runDeploy (/home/nathan/test/game/node_modules/hardhat-deploy/src/DeploymentsManager.ts:844:5)
    at Environment._runTaskDefinition (/home/nathan/test/game/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
```

**Comment by antoinedc** [comment]
Ah nice! I was suspecting it had something to do with signers as well. But I'm not sure why Ethernal makes this fail, there isn't request sent or signed through the package...
However, I've seen that there might be some conflicts between packages using hardhat-ethers/hardhat-ethers-deploy, maybe it comes from there. I will talk to the Hardhat team about this, maybe they've an idea about what's going on here.

In any case, I'm glad you were able to fix this!!

**Comment by qSlnz** [comment]
Yes I also think it must be a conflict between packages. Anyway thanks for your help, and ça fait plaisir de voir des projets crypto français ;) Bonne continuation !

**Comment by antoinedc** [comment]
Ahah merci :)
