### ISSUE TITLE
Broken support for Hardhat 2.22.10

### ISSUE THREAD

**Issue by MMujtabaRoohani** [antoinedc/hardhat-ethernal#40]
The plugin is failing with the following stack trace with hardhat [`^2.22.10`](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.22.10)

```
TypeError: (0 , config_1.experimentalAddHardhatNetworkMessageTraceHook) is not a function
    at Object.<anonymous> (/mnt/c/Users/.../node_modules/hardhat-ethernal/src/index.ts:25:46)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Object.require.extensions.<computed> [as .js] (/mnt/c/Users/.../node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/mnt/c/Users/.../hardhat.config.ts:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
```

While it is working flawlessly with previous versions of hardhat `<= 2.22.9`. As far as I can see, we need to stop using `experimentalHardhatNetworkMessageTraceHooks` as it is removed by hardhat in `2.22.10`

**Comment by antoinedc** [comment]
Hi! Thanks for the report, will work on fixing it this week :)

**Comment by iamIcarus** [comment]
> Hi! Thanks for the report, will work on fixing it this week :)

Submitted a PR for this, have a quick review

**Comment by antoinedc** [comment]
Thanks a lot for the PR! I merged it & released a new version. Let me know if that works now.

**Comment by iamIcarus** [comment]
Thanks, working now for `Hardhat 2.22.10`
